### PR TITLE
preserve capital after quote

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by dstillman** [comment]
This seems to be preserving the capital after any quote, though? For example:

`"Here is a “Test” of of the sentence-caser": "Here is a “test” of the sentence-caser",`

```
1) Zotero.Utilities
       sentenceCase
         should stably perform sentence-casing:

      AssertionError: expected 'Here is a “Test” of of the sentence-c…' to equal 'Here is a “test” of the sentence-caser'
      + expected - actual

      -Here is a “Test” of of the sentence-caser
      +Here is a “test” of the sentence-caser
```

All we want to do is protect the character after opening quotation marks (`"`, `'`, `“`, and `‘`). So even the test case here isn't right:

`"<i>Erratum:</i> “Analyzing the Growth of InₓGa₁₋ₓN/GaN Superlattices in Self-Induced GaN Nanowires by x-Ray Diffraction”": "<i>Erratum:</i> “Analyzing the growth of InₓGa₁₋ₓN/GaN superlattices in self-induced GaN nanowires by x-ray diffraction”"`

"Analyzing" is in the middle of the sentence, so it shouldn't be left capitalized.)

**Comment by retorquere** [comment]
Ah I see! Coming up.

**Comment by retorquere** [comment]
In

> “If you don’t actually care for somebody, how can you help them?”: Exploring Young People’s Core Needs in Mental Healthcare—Directions for Improving Service Provision

do you want `Exploring` capitalized, or not?

**Comment by dstillman** [comment]
> do you want Exploring capitalized, or not?

No. Zotero does that automatically for styles that require it (which implies that some don't):

https://www.zotero.org/support/kb/sentence_casing#sentence_case_and_subtitles

**Comment by retorquere** [comment]
I have the change ready and pushed to my own clone but the PR isn't updating

**Comment by retorquere** [comment]
I was pushing the wrong branch

**Pull request closed without merging**
